### PR TITLE
update maintainers

### PR DESCRIPTION
**Pull request by ndeloof**
This updates the Compose Spec maintainers to reflect the actual status:

- David Killmon had no activity on the spec for months
- Ulysses Souza has been maintainer on docker-compose for years so is 200% legitimate to help us evolve the compose file format, in addition to the many contributions he made on compose-go.

### CODE REVIEW

**Review by glours — APPROVED** [review]
LGTM

**Review by justincormack — APPROVED** [review]

**Review by nebuk89 — APPROVED** [review]
LGTM

**Review by EricHripko — APPROVED** [review]
Looks great ✅

**Comment by ndeloof** [comment]
We've reached the "66% of the current maintainers" limit required by our [governance policy](https://github.com/compose-spec/compose-spec/blob/master/GOVERNANCE.md#removal-of-inactive-maintainers)
I'll keep this PR open for a few more day in case anyone want to comment, then merge it

**Pull request merged**
