### PR TITLE
typo: missing word in sentence

### PR DESCRIPTION
**Pull request by denkquer**
**Typo in spec.md**

Missing word in subsection "external" of section "Volumes top-level element"

_just close this, if simple typo pr are not appreciated._

### CODE REVIEW

**Comment by EricHripko** [comment]
cc @kohidave

**Review by EricHripko — APPROVED** [review]
Looks great ✅ Thank you for putting this contribution together @denkquer 👍

**Comment by EricHripko** [comment]
@denkquer could you please sign your commit(s) off so that DCO check succeeds?

**Comment by denkquer** [comment]
@EricHripko  done! sorry for the inconvenience.

**Comment by EricHripko** [comment]
No worries at all - thank you for the quick turnaround 👍 This PR will be merged once (at least) one more reviewer approves.

**Review by ndeloof — APPROVED** [review]

**Pull request merged**
