### PR TITLE
Fix indentation on examples in the Deployment spec

### PR DESCRIPTION
**Pull request by mikesir87**
**What this PR does / why we need it**:

Some indentation fixes/alignment with the rest of the document

### CODE REVIEW

**Comment by EricHripko** [comment]
cc @kohidave

**Review by EricHripko — COMMENTED** [review]
Hi @mikesir87 👋 Thank you for putting together this contribution. From what I understand, this replaces 4-space indentation with 2-space indentation in the examples for consistency, is that right?

**Comment by mikesir87** [comment]
That's correct. Even within some snippets, different indentation was being used. So, this just helped fixed all of the spots using four-space to two-space 👍

**Comment by EricHripko** [comment]
ah that explains the strange diffs - thank you for clarifying 👍

**Review by EricHripko — APPROVED** [review]
Looks great ✅ Thank you again for this contribution 🙌

**Review by ndeloof — APPROVED** [review]

**Pull request merged**
