### PR TITLE
fix external links

### PR DESCRIPTION
**Pull request by dvdksn**
Signed-off-by: David Karlsson <david.karlsson@docker.com>

**What this PR does / why we need it**:

- Fix bad formatting for links (double parentheses)
- Replace dead links to permissions-calculator.org
- Update link protocol to use https instead of http
- Update link to chris.beams.io, which was redirected

**Which issue(s) this PR fixes**:

N/A

### CODE REVIEW

**Review by laurazard — APPROVED** [review]

**Comment by laurazard** [comment]
@dvdksn can you rebase this?

**Comment by dvdksn** [comment]
done @laurazard

**Comment by glours** [comment]
@dvdksn you need to run `make docs` locally to generate the `spec.md` file according to your changes

**Comment by dvdksn** [comment]
ah ok @glours - done

**Pull request merged**
