### PR TITLE
improved illustrative example in spec.md file Signed-off-by: Prince Ogabi ogabiprince@gmail.com

### PR DESCRIPTION
**Pull request by Omoba5**
**What this PR does / why we need it**:
The initial illustrative example was not as easy to read and not as elaborate

**What is the problem you're trying to solve**
I created a better version of the sketch in the illustrative example without tampering with its meaning.

Signed-off-by: Prince Ogabi <ogabiprince@gmail.com>

### CODE REVIEW

**Comment by ndeloof** [comment]
why did you closed this PR ?

**Comment by Omoba5** [comment]
Hi there, 

This is my first opensource contribution, so I am not really sure how everything works, I have read the Code of Conducts and Guidelines though. I got an error saying I didn't sign the commit, but I did according to the guidelines, so I tried to do so again but it bot still saw it as not signed so I closed it again to see how the others did theirs

**Comment by ndeloof** [comment]
`git amend --signoff`, the `git push --force` should solve this

**Comment by ndeloof** [comment]
Discussing about this with the compose team, I wonder we could rely on https://github.blog/2022-02-14-include-diagrams-markdown-files-mermaid/ for this diagram, so we keep it simple to maintain while we get a reasonable human friendly rendering. WDYT?

**Comment by Omoba5** [comment]
The commands did not work, but anyway, I have decided to delete the branch and try again from scratch- this time with the -s option for automatic signing. 

As regard the mermaid markdown, I think it is a great idea but even better is from me to upload the file with a *.drawio.svg extension, this will both give a beautiful rendering as well as allow for easy maintenance. I have tested it. you could give it a try too, just go over to draw.io and chose open, then select the file locally.

I will be creating another branch now and sending the PR again. Let me know what you decide. Thank you sir.

**Comment by ndeloof** [comment]
the benefits of mermaid is that this still is (reasonably) readable without formatting, so make code review easier, and also does not require a dedicated editor for updates. svg makes better rendering, but maintenance will be way harder

**Comment by ndeloof** [comment]
Contributions always are welcome but you should first create an issue and discuss with maintainers on the preferred aroach before investing too much of your spare time.

Mouse-driven illustration is obviously easier for the author, but makes it hard to compare and maintain. That's why most RFC use plain text illustrations.

**Comment by ndeloof** [comment]
I made my own attempt using mermaid. While not as nice as your proposed svg, I think this still provides a better rendering without sacrifice for maintenability: https://github.com/compose-spec/compose-spec/pull/344

actually, easier to maintain than the original ascii art diagram

**Comment by Omoba5** [comment]
I gave it a shot again. Too far to back down, I will commit now, let me know what you think

**Comment by Omoba5** [comment]
😄

I just saw your message after committing mine. I was too engrossed. Well, I have done my best. 😄

I sent you a connect on LinkedIn,  I hope that's okay.

**Pull request closed without merging**
