### PR TITLE
fix missing config in compose example

### PR DESCRIPTION
**Pull request by patrickbaber**
**What this PR does / why we need it**:

Fixes a compose example. The paragraph above is mentioning a config `my_other_config`, which is missing in the example.

> The `redis` service does not have access to the `my_other_config` config.

### CODE REVIEW

**Review by EricHripko — APPROVED** [review]
Great spot @patrickbaber - thank you for taking the time to improve the spec 🙂 PR looks good to me ✅

**Comment by EricHripko** [comment]
Please note that you will need to sign off the commit with your name + email for DCO check to pass 👀

**Review by ndeloof — APPROVED** [review]

**Review by chris-crone — APPROVED** [review]
LGTM, thanks!

**Comment by patrickbaber** [comment]
> Please note that you will need to sign off the commit with your name + email for DCO check to pass 👀

That was new to me. Done!

**Pull request merged**
