### PR TITLE
fix: broken internal links

### PR DESCRIPTION
**Pull request by dvdksn**
Signed-off-by: David Karlsson <35727626+dvdksn@users.noreply.github.com>

**What this PR does / why we need it**:

Fixes two broken internal links

**Which issue(s) this PR fixes**:

### CODE REVIEW

**Review by glours — APPROVED** [review]

**Review by aevesdocker — APPROVED** [review]
Thank you @dvdksn 🙏

**Review by Kryslynn93 — COMMENTED** [review]
ok

**Comment by Kryslynn93** [comment]
approve

**Review by Kryslynn93 — COMMENTED** [review]
approve

**Pull request merged**
