### PR TITLE
Correct anchor links in Compose File section

### PR DESCRIPTION
**Pull request by djsipe**
Several anchor links did not work correctly.

**What this PR does / why we need it**:
This is a minor fix to the links in the Markdown.  It was bugging me that they didn't link properly so here is the PR! :)

### CODE REVIEW

**Comment by ndeloof** [comment]
Thanks for your contribution, please ensure you sign-off commits or we can't legally approve this PR

**Comment by djsipe** [comment]
I attempted to sign-off following the docs in Github.  Not sure if it worked or how to verify.  Fingers crossed!

**Comment by EricHripko** [comment]
This PR appears to have 0 Files Changed. We had some other community PRs fixing links in Markdown, could it be that this issue is already addressed?

**Comment by djsipe** [comment]
Very possible.  You can ignore this if it's not adding value.  Thanks!

**Pull request closed without merging**
