### PR TITLE
build: fix typo

### PR DESCRIPTION
**Pull request by williballenthin**
**What this PR does / why we need it**: fixes trivial typo in documentation

**Which issue(s) this PR fixes**: n/a - trivial typo. can open an issue if strictly required.

### CODE REVIEW

**Comment by EricHripko** [comment]
CC @kohidave

**Review by EricHripko — APPROVED** [review]
Looks great ✅ Thank you for taking the time to submit this contribution 🙂

**Comment by EricHripko** [comment]
@williballenthin could you please add a sign-off on the commit(s) in this PR so that the checks pass?

**Review by ndeloof — APPROVED** [review]

**Comment by EricHripko** [comment]
poke @williballenthin

**Comment by bjmmedeiros** [comment]
Hello!
Even though I'm not used to contributing to this project, could we include another typo fix in this one?
I was about to open a PR, but gladly I found this one still active.

line 1368: 
same Compose file. Defining a secret in the top-level `secrets` MUTS NOT imply granting any service access to it.

Fix small typo in the spec.md (MUTS -> MUST):
same Compose file. Defining a secret in the top-level `secrets` MUST NOT imply granting any service access to it.

**Comment by EricHripko** [comment]
Hi @bjmmedeiros! Thank you for taking the time to make Compose spec better 🙌 You might want to submit a separate PR (either including these fixes or not) to get this done sooner. We need a sign-off from the author, which is why this one hasn't been landed yet.

**Comment by bjmmedeiros** [comment]
Hey @EricHripko !
I went ahead and created a new PR #183 with this small change.
It seems that the original issue with this pull request has been solved by another commit [406feef](https://github.com/compose-spec/compose-spec/commit/406feefd7c06ebf3e43c7f3918f3b7c3207ad9bf#diff-59cf752622933ceff72c103aa4de7df798636517c6e8e7c5accac2b4db10e1c5), so maybe we should abandon this PR?

**Comment by williballenthin** [comment]
using the other PR with similar changes is a good idea, i'll close out this PR.

**Comment by EricHripko** [comment]
Thank you for splitting the PR up! I'll take a look at the new one now 🙂

**Pull request closed without merging**
