### PR TITLE
Improved diagram

### PR DESCRIPTION
**Pull request by Omoba5**
**What this PR does / why we need it**:
The initial illustrative example was not as easy to read and not as elaborate

**What is the problem you're trying to solve**
I created a better version of the sketch in the illustrative example without tampering with its meaning. I used mermaid markdown because I was advised to give great priority to Maintainability. 
Now the illustration is beautiful, maintainable and still being meaningful.

### CODE REVIEW

**Comment by ndeloof** [comment]
you have to run `make spec` to generate the one-pager spec file and add it to your commit

**Comment by Omoba5** [comment]
I have done that now.

**Comment by glours** [comment]
I don't know why but looking at the changes only show a modification which may not link to the purpose of this Pull Request

**Comment by Omoba5** [comment]
It's because there was no file change in the last commit. I just ran `make spec` as advised. Please check the series of commits to see the changes. Or do you want me to rebase and then push as 2 commits?

**Comment by Omoba5** [comment]
Oh, I just saw what you are talking about. the last commit reverted the real reason for the PR. Will rebasing and pushing all together fix this?

**Comment by ndeloof** [comment]
the issue is you made change on `spec.md`, which is not the source of truth. You should have edited `02-model.md` and ran `make spec` to produce the one-pager.
Also, feel free to squash your commits so we don't keep all the back and forth after merge

**Comment by glours** [comment]
@Omoba5 unfortunately no, the changes without selecting a specific commit should show all the changes from all commits, and here I see only 1 change unrelated with the diagram modification.
The issue here, is that your changes should be done in the `https://github.com/compose-spec/compose-spec/blob/master/02-model.md` file, the `spec.md` is generated and should not be modified directly

**Comment by Omoba5** [comment]
Okay, I will implement that. Thank you for being patient with me.

**Comment by Omoba5** [comment]
Done! This has to be it.

**Comment by ndeloof** [comment]
Merged, thanks a lot for your contribution

**Pull request closed without merging**
