### PR TITLE
remove redundant dash

### PR DESCRIPTION
**Pull request by saied89**
There is a redundant dash in the title of _specifying byte values_ section that is wrong and furthermore prevents links to this section from working. E.g [here](https://github.com/compose-spec/compose-spec/blob/master/spec.md#shm_size) and [here](https://github.com/compose-spec/compose-spec/blob/master/deploy.md#memory)

### CODE REVIEW

**Review by EricHripko — APPROVED** [review]
Looks great ✅ Thank you for this contribution @saied89 🙌 Could you please sign your commit off to make sure that PR checks pass?

**Comment by EricHripko** [comment]
cc @kohidave

**Comment by saied89** [comment]
I made the PR using Github's online editor without cloning. Now that I clone and try to run the git sign off command, the check doesn't seem to pass. 
Can't say have experience with this sign-off thing. Can you tell me what I'm doing wrong?

**Comment by ndeloof** [comment]
@saied89 `git commit (--amend) -s`
sign-off is actually just a line of text added to your commit message:
```
Commit message blah blah

Signed-off-by: John Doe <jdoe@acme.com>
```

**Comment by saied89** [comment]
I finally got around to fix it. 
Sorry it took so long.

**Comment by EricHripko** [comment]
@ndeloof, could you approve? 🙂

**Review by ndeloof — APPROVED** [review]

**Pull request merged**
