### PR TITLE
Refer to docker/compose-cli

### PR DESCRIPTION
**Pull request by decentral1se**
**What this PR does / why we need it**:

Following https://github.com/docker/compose-cli/issues/901#issuecomment-728803596.

**Which issue(s) this PR fixes**:

N/A

### CODE REVIEW

**Comment by EricHripko** [comment]
Hi @decentral1se 👋 Thank you for this contribution! Could you please make sure that your commits are [signed](https://github.com/compose-spec/compose-spec/blob/master/CONTRIBUTING.md#sign-your-work)?

**Comment by decentral1se** [comment]
Verified and rebased. Now a DCO!? :see_no_evil:

**Comment by EricHripko** [comment]
Thank you for addressing the feedback and apologies for the DCO hassle 👍

**Comment by EricHripko** [comment]
cc @kohidave also

**Review by EricHripko — APPROVED** [review]
Looks great ✅ Thank you for this contribution 🎉

**Review by ndeloof — APPROVED** [review]

**Pull request merged**
