### PR TITLE
introduce support for cgroup=host|private

### LINKED ISSUE #148: Missing composer specification equivalent for --cgroupns=[host|private]/API1.41
On hosts with "only" a unified cgroup v2 controller hierarchy (that is, a "pure" cgroups v2 hierarchy) Docker now defaults (unless configured otherwise) to automatically creating private cgroup namespaces for created containers. The rationale here is to reduce leakage of potentially sensitive information about the cgroup hierarchy and configuration of the host, and thus other containers. Still, there are valid usecases to allow only specific containers to use the initial (host) cgroup namespace, especially for system diagnosis containers. For instance, the well-known [cAdvisor](https://github.com/google/cadvisor) ("*provides container users an understanding of the resource usage and performance characteristics of their running containers*").

For such usecases, docker run introduced the CLI flag --cgroupns=[host|private] as of Docker-CE 20.0.0 and API 1.41.

Unfortunately, the current compose specification doesn't provide any means to controlling cgroup namespace creation or sharing. This makes it impossible to use system diagnosis containers, such as cAdvisor, ... on cgroup v2 unified hierarchy-only systems anymore with compose-based deployment tools.

This situation would be solved by adding a cgroup field to service objects that would allow to specify the values of either "private" or "host", mirroring today's CLI flag functionality for handling the cgroup namespace creation for new containers.

```yaml
services:
  foo:
    pid: host
    cgroup: host # might be "cgroupns" instead if parity with CLI flag is sought after, but breaks symmetry with pid namespaces.
```

Nota bene: mirror [docker/compose issue #8167](https://github.com/docker/compose/issues/8167)

### PR DESCRIPTION
**Pull request by ndeloof**
**Which issue(s) this PR fixes**:
Fixes #148
see https://github.com/docker/compose/issues/8167

### CODE REVIEW

**Review by ulyssessouza — APPROVED** [review]

**Comment by thediveo** [comment]
https://github.com/compose-spec/compose-spec/issues/148#issuecomment-834639159 lists the docker CLI allowed values which include an empty string:

```
docker run --help | grep cgroup
      --cgroupns string                Cgroup namespace to use (host|private)
                                       'host':    Run the container in the Docker host's cgroup namespace
                                       'private': Run the container in its own private cgroup namespace
                                       '':        Use the cgroup namespace as configured by the
                                                  default-cgroupns-mode option on the daemon (default)
```

Would this be also needed to be carried over to the compose world?

**Comment by ndeloof** [comment]
@thediveo `cgroup: ""` would probably better be defined in a compose file by not setting `cgroup` attribute. Then the actual behavior would be left to the container runtime (out of the scope of the compose spec) which is indeed  `default-cgroupns-mode option` on docked, but could be a different choice with alternative runtimes.

**Comment by BorderCloud** [comment]
+1

**Review by glours — APPROVED** [review]

**Comment by thediveo** [comment]
This has also finally landed in the documentation: https://docs.docker.com/compose/compose-file/05-services/#cgroup

**Pull request merged**
