### PR TITLE
Correct typo in `05-services.md`

### PR DESCRIPTION
**Pull request by allanlewis**
**What this PR does / why we need it**: Corrects a typo

**Which issue(s) this PR fixes**: n/a - I hope that's ok given the nature of this change 🙏

### CODE REVIEW

**Review by laurazard — APPROVED** [review]
LGTM, thanks :)

**Comment by laurazard** [comment]
Ahh, @allanlewis you'll have to run `make spec` to update the full `spec.md` file with your changes.

**Comment by allanlewis** [comment]
Sure, done ✅

**Comment by allanlewis** [comment]
I fixed the signoff.

**Comment by allanlewis** [comment]
Properly rebased now.

**Review by ulyssessouza — APPROVED** [review]
LGTM

**Pull request merged**
