### PR TITLE
fixing grammar mistake

### PR DESCRIPTION
**Pull request by MattBussing**

### CODE REVIEW

**Comment by EricHripko** [comment]
Hi @MattBussing 👋 Thank you for putting this contribution together! Could you please add a [sign-off](https://github.com/compose-spec/compose-spec/blob/master/CONTRIBUTING.md#sign-your-work) so that the checks pass?

**Review by ndeloof — APPROVED** [review]

**Comment by MattBussing** [comment]
@EricHripko , new to signing off. Did that fix it? Is there anything else I need to do? Thank you for your help and patience!

**Comment by glours** [comment]
@MattBussing can you signoff your commit please? 
You can follow the instruction here: https://github.com/compose-spec/compose-spec/pull/220/checks?check_run_id=5163771856

**Comment by MattBussing** [comment]
@glours , thanks for posting that link! I think I got it working this time.

**Review by ndeloof — APPROVED** [review]

**Comment by MattBussing** [comment]
Thanks everyone!

**Pull request merged**
